check_on: branch_name

rules:
  - regex: ^feature/
    amount: 1
    reviewers:
      - user:racoon63
  - regex: "^dependabot/"
    reviewers:
      - user:patricklubach
  - default: true
    reviewers:
      - user:patricklubach
