check_on: branch_name

rules:
  - regex: ^feature/
    amount: 1
    approvers:
      - user:racoon63
  - regex: "^dependabot/"
    approvers:
      - user:patricklubach
  - default: true
    approvers:
      - user:patricklubach
